### ISSUE TITLE
Improve mail validation

### ISSUE THREAD

**Issue by encrypt94** [jrmi/ricochet.js#50]
Hello, 
i stumbled into ricochet.js while trying to install airboardgame.
I tried to register using a mail with a gTLD (>3 letters) and got an invalid mail message.
Looks like the regex you're using [here in the validation](https://github.com/jrmi/ricochet.js/blob/1c6a4ea02f3fc31a695bb6b4c267fa758ba3d60f/src/site.js#L11)  doesn't work with IDNs, TLDs with more than three characters  and its' known for [catastrophic backtracking problems](https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression).

Can you please consider using something like <http://emailregex.com/>

Cheers

**Comment by jrmi** [comment]
Yes sure, thanks for reporting.

**Comment by jrmi** [comment]
The new version with regex improvement has been deployed. Tell me if it's not working for you.
